config/routes.rb
Earful::Application.routes.draw do

  root :to => "content#index"

  match '/wall/ajax_load_post_details' => "wall#ajax_load_post_details"
  match '/wall/public/ajax_subscribe/:id' => "wall#ajax_subscribe", :as => :wall_ajax_subscribe
  match '/wall/public/ajax_unsubscribe/:id' => "wall#ajax_unsubscribe", :as => :wall_ajax_unsubscribe
  match '/wall/unsubscribe/:id' => "wall#unsubscribe", :as => :wall_unsubscribe
  match '/wall/search/:tag' => "wall#search", :as => :wall_search
  match '/wall/public/ajax_post' => "wall#ajax_public_post", :as => :wall_ajax_public_post
  match '/wall/ajax_post' => "wall#ajax_post", :as => :wall_ajax_post

  match '/streams/ajax_post' => "streams#ajax_post", :as => :streams_ajax_post
  match '/streams/pin_user' => "streams#pin_user", :as => :streams_pin_user
  match '/streams/ajax_unpin_user/:id' => "streams#ajax_unpin_user", :as => :streams_ajax_unpin_user
  match '/streams/ajax_load_posts' => "streams#ajax_load_posts", :as => :streams_ajax_load_posts
  match '/streams/like/:id' => "streams#ajax_like", :as => :streams_ajax_like
  match '/streams/repin/:id' => "streams#ajax_repin", :as => :streams_repin
  match '/streams/ajax_post_repin' => "streams#ajax_post_repin", :as => :streams_ajax_post_repin
  match '/streams/ajax_load_likes/:id' => "streams#ajax_load_likes", :as => :streams_ajax_load_likes
  match '/streams/comment/:id' => "streams#ajax_comment", :as => :streams_ajax_comment
  match '/streams/ajax_load_comments' => "streams#ajax_load_comments"
  match '/streams/ajax_delete_post/:id' => "streams#ajax_delete_post", :as => :streams_ajax_delete_post

  match '/content/ajax_load_comments' => "content#ajax_load_comments", :as => :content_ajax_load_comments
  match '/content/comment/:id' => "content#ajax_comment", :as => :content_ajax_comment
  match '/privacy-policy' => "content#privacy_policy"

  resources :users do
    member do
      get "wall", "fb_connect", "profile"
    end

    collection do
      get "ajax_find_friend", "invite"
      post "send_invitation", "fb_register"
    end
  end

  resources :posts

  resources :notifications do
    collection do
      get "ajax_load"
      post "ajax_ack"
    end
  end

  resources :login do
    collection do
      get "fb_login", "retrieve_password", "reset_password"
      post "mail_guid", "save_password"
    end
  end

  resources :wall, :except => :show do
    collection do
      get "my_walls", "friends", "my_likes"
    end
  end

  resources :streams, :except => :show

  match '/wall/:slug' => "wall#view", :as => :view_wall

  resources :friends do
    collection do
      get "find"
      post "search"
    end
  end

  match '/friend_requests/' => "friend_requests#index", :as => :friend_requests_index
  match '/friend_requests/update/:id/:status' => "friend_requests#update", :as => :friend_requests_update
  match '/friend_requests/new/:id' => "friend_requests#new", :as => :new_friend_requests
  match '/friend_requests/:id/ajax_new' => "friend_requests#ajax_new", :as => :ajax_new_friend_requests

  match '/email/unsubscribe/:key' => "email_unsubscribe#index", :as => :email_unsubscribe
  match '/facebook/invited' => "content#facebook_invited"
  match '/facebook' => "content#facebook_app"
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  layout "application"
  before_filter :init

  def init
    @active_tab = "friends"
  end

  def index
    get_friends
    @user.acknowledge_new_friends
  end

  def find
  end

  def search
    @results = User.search_friend( params[:friend], @user )
  end

  def destroy
    @user.remove_friendship(params[:id])
    
    flash.now[:notice] = "#{User.find(params[:id]).first_and_last_name} was removed from your friends list"
    get_friends
    render :template => "friends/index"
  end

  private

  def get_friends
    @requests = @user.friend_requests
    @friends = @user.confirmed_friends.sort{|a,b| a.first_name <=> b.first_name }
  end
end

app/views/friends/_find_form.html.erb
<%= form_for :friend, :url => search_friends_url, :html => { :class => "custom" } do | f | %>
  <%= f.label :first_name, "First Name" %>
  <%= f.text_field :first_name, :class => "four" %>

  <%= f.label :last_name, "Last Name" %>
  <%= f.text_field :last_name, :class => "four" %>

  <%= f.label :email, "Email" %>
  <%= f.text_field :email, :class => "four" %>

  <%= f.submit "Submit", :class => "button" %>
<% end %>

app/views/friends/_list.html.erb
<div class="row">
  <div class="twelve columns">

    <h1 style="width: 20%;" class="left">Friends</h1>

    <div class="friends-list-buttons right clearfix">
      <%= render :partial => "shared/find_friends_buttons" %>
    </div>

    <% if !@friends.empty? %>
      <table width="100%" class="friends-list">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @friends.each do | f | %>
            <tr>
              <td>
                <%= link_to profile_user_url(f) do %><%= render_profile_photo( f, "32x32", "friends-small-image" ) %><% end %>
                <%= link_to f.first_and_last_name, profile_user_url(f) %>
              </td>
              <td><%= f.email %></td>
              <td style="text-align: center;">
                <%= link_to "Remove", friend_url(f), :method => :delete, :confirm => "Are you sure you want to remove this friend?", :class => "small button" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p style="clear: both;">You don't have any friends yet</p>
    <% end %>
  </div>
</div>

app/views/friends/find.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Find Friends<% end %>

<%= raw render_flash( flash ) %>

<h1>Find Friends</h1>

<%= render :partial => "friends/find_form" %>

app/views/friends/index.html.erb
<% content_for :title do %>
  <%= Constants::SiteName %> - Friends
<% end %>

<%= raw render_flash( flash ) %>

<%= render :partial => "friend_requests/list" %>
<%= render :partial => "friends/list" %>

app/views/friends/search.html.erb
<% content_for :title do %>
  <%= Constants::SiteName %> - Search Results
<% end %>

<h1>Search For Friends</h1>
<%= render :partial => "find_form" %>

<h1>Search Results</h1>

<% if !@results.empty? %>
	<table width="100%">
		<thead>
			<tr>
        <th></th>
				<th>Name</th>
				<th>Email</th>
        <th></th>
			</tr>
		</thead>

		<tbody>
			<% @results.each do | user | %>
				<tr>
          <td><%= link_to profile_user_url(user) do %><%= render_profile_photo( user, "64x64" ) %><% end %></td>
					<td><%= link_to user.first_and_last_name, profile_user_url(user) %></td>
					<td><%= link_to user.email, "mailto:#{user.email}" %></td>
          <td><%= link_to "Send Friend Request", new_friend_requests_url(user), :class => "button" %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<p>No results found</p>
<% end %>