config/routes.rb
Earful::Application.routes.draw do

  root :to => "content#index"

  match '/wall/ajax_load_post_details' => "wall#ajax_load_post_details"
  match '/wall/public/ajax_subscribe/:id' => "wall#ajax_subscribe", :as => :wall_ajax_subscribe
  match '/wall/public/ajax_unsubscribe/:id' => "wall#ajax_unsubscribe", :as => :wall_ajax_unsubscribe
  match '/wall/unsubscribe/:id' => "wall#unsubscribe", :as => :wall_unsubscribe
  match '/wall/search/:tag' => "wall#search", :as => :wall_search
  match '/wall/public/ajax_post' => "wall#ajax_public_post", :as => :wall_ajax_public_post
  match '/wall/ajax_post' => "wall#ajax_post", :as => :wall_ajax_post

  match '/streams/ajax_post' => "streams#ajax_post", :as => :streams_ajax_post
  match '/streams/pin_user' => "streams#pin_user", :as => :streams_pin_user
  match '/streams/ajax_unpin_user/:id' => "streams#ajax_unpin_user", :as => :streams_ajax_unpin_user
  match '/streams/ajax_load_posts' => "streams#ajax_load_posts", :as => :streams_ajax_load_posts
  match '/streams/like/:id' => "streams#ajax_like", :as => :streams_ajax_like
  match '/streams/repin/:id' => "streams#ajax_repin", :as => :streams_repin
  match '/streams/ajax_post_repin' => "streams#ajax_post_repin", :as => :streams_ajax_post_repin
  match '/streams/ajax_load_likes/:id' => "streams#ajax_load_likes", :as => :streams_ajax_load_likes
  match '/streams/comment/:id' => "streams#ajax_comment", :as => :streams_ajax_comment
  match '/streams/ajax_load_comments' => "streams#ajax_load_comments"
  match '/streams/ajax_delete_post/:id' => "streams#ajax_delete_post", :as => :streams_ajax_delete_post

  match '/content/ajax_load_comments' => "content#ajax_load_comments", :as => :content_ajax_load_comments
  match '/content/comment/:id' => "content#ajax_comment", :as => :content_ajax_comment
  match '/privacy-policy' => "content#privacy_policy"

  resources :users do
    member do
      get "wall", "fb_connect", "profile"
    end

    collection do
      get "ajax_find_friend", "invite"
      post "send_invitation", "fb_register"
    end
  end

  resources :posts

  resources :notifications do
    collection do
      get "ajax_load"
      post "ajax_ack"
    end
  end

  resources :login do
    collection do
      get "fb_login", "retrieve_password", "reset_password"
      post "mail_guid", "save_password"
    end
  end

  resources :wall, :except => :show do
    collection do
      get "my_walls", "friends", "my_likes"
    end
  end

  resources :streams, :except => :show

  match '/wall/:slug' => "wall#view", :as => :view_wall

  resources :friends do
    collection do
      get "find"
      post "search"
    end
  end

  match '/friend_requests/' => "friend_requests#index", :as => :friend_requests_index
  match '/friend_requests/update/:id/:status' => "friend_requests#update", :as => :friend_requests_update
  match '/friend_requests/new/:id' => "friend_requests#new", :as => :new_friend_requests
  match '/friend_requests/:id/ajax_new' => "friend_requests#ajax_new", :as => :ajax_new_friend_requests

  match '/email/unsubscribe/:key' => "email_unsubscribe#index", :as => :email_unsubscribe
  match '/facebook/invited' => "content#facebook_invited"
  match '/facebook' => "content#facebook_app"
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  layout "full_page"
  before_filter :init, :except => [:ajax_load_posts, :ajax_load_likes, :ajax_load_comments]

  def init
    @active_tab = "streams"
    if @user.nil?
      redirect_to login_index_url
    end
  end

  def index
    get_wall_configs
    @wall_post = WallPost.new
    @wall_pinning = WallPinning.new
    render :layout => "full_page"
  end

  def ajax_post
    @wall_pinning_id = params["wall_pinning_id"]
    user_is_me = @user.is_me?(params[:wall_post][:user_id])

    if !params[:wall_post][:post_text].blank?
      @wall_post = WallPost.new(params[:wall_post])
      @wall_post.post_type = "user_wall"
      @wall_post.poster_user = @user
      Util.strip_html(@wall_post.post_text)
      @wall_post.get_track_details
      @wall_post.save
      Notification.create(:user_id => @wall_post.user_id, :notifiable_type => "wall_post", :notifiable_id => @wall_post.id, :notification_type => "user_wall_post") if @user.id != @wall_post.user_id
      UserMailer.deliver_wall_post( @user, @wall_post.user, @wall_post ) if !user_is_me && Constants::DeliverMail && EmailUnsubscribe.find_by_email_and_set(@wall_post.user.email, true).nil?
      respond_to do |format|
        format.js{ render "streams/ajax/ajax_post" }
      end
    else
      render :text => ""
    end
  end

  def pin_user
    @wall_pinning = WallPinning.new(params[:wall_pinning])

    if( @user.is_my_friend?(@wall_pinning.pinned_user_id) )
      @wall_pinning.slot = WallPinning.next_slot(@user.id)
      @wall_pinning.user_id = @user.id
      @wall_pinning.save
      flash.now[:notice] = "Your friend was pinned"
    end

    @wall_post = WallPost.new
    @wall_pinning = WallPinning.new

    get_wall_configs

    render :template => "streams/index"
  end

  def ajax_unpin_user
    @wall_pinning = WallPinning.find(params[:id])
    @old_wp_id = @wall_pinning.id

    if @wall_pinning.user_id == @user.id
      WallPinning.reorg_slots(@wall_pinning)
      @wall_pinning.destroy
    end

    respond_to do |format|
      format.js{ render "streams/ajax/ajax_unpin_user" }
    end
  end

  def ajax_load_posts
    @wall_pinning = WallPinning.find(params["wall_pinning_id"])
    @posts = @wall_pinning.pinned_user.recent_wall_posts(params["page"].to_i * Constants::WallPostsPerPage, Constants::WallPostsPerPage)
    respond_to do |format|
      format.js{ render "streams/ajax/ajax_load_posts" }
    end
  end

  def ajax_like
    @post = WallPost.find(params[:id])

    if WallPostLike.first(:conditions => ["wall_post_id=? AND liker_id=?", params[:id].to_i, @user.id]).nil?
      wpl = WallPostLike.create({:wall_post_id => params[:id], :liker_id => @user.id})
      Notification.create(:user_id => @post.poster_user_id, :notifiable_type => "wall_post_like", :notifiable_id => wpl.id, :notification_type => "post_like") if @user.id != @post.poster_user_id
      @post = WallPost.find(params[:id])
      respond_to do |format|
        format.js{ render "streams/ajax/ajax_like" }
      end
    else
      render :text => ""
    end
  end

  def ajax_repin
    @post = WallPost.find(params[:id])
    @new_post = WallPost.new
    @new_post.attributes = @post.attributes
    @new_post.user_id = @user.id
    @new_post.poster_user_id = @user.id
    @new_post.repin_parent_id = @post.repin_parent_id.nil? ? @post.id : @post.repin_parent_id
    #@repin_text = @post.repin_content
    respond_to do |format|
      format.js{ render "streams/ajax/ajax_repin" }
    end
  end

  def ajax_post_repin
    @post = WallPost.new(params[:wall_post])
    if !@user.nil? && @user.is_me?(@post.user_id)
      Util.strip_html(@post.post_text)
      @post.post_text += "<br />#{params[:repin_content]}"
      @post.post_type = "user_wall"
      @post.get_track_details
      @post.save
      respond_to do |format|
        format.js{ render "streams/ajax/ajax_post_repin" }
      end
    else
      render :text => ""
    end
  end

  def ajax_comment
    @post = WallPost.find(params[:id])
    @comment = WallPostComment.new({:wall_post_id => @post.id, :commenter_id => @user.id, :comment => params[:wall_post_comment][:comment]})
    Util.strip_html(@comment.comment)
    if @comment.valid?
      @comment.save
      @post.create_notifications(@comment)
      respond_to do |format|
        format.js{ render "streams/ajax/ajax_comment" }
      end
      return
    end
    render :text => ""
  end

  def ajax_load_likes
    @post = WallPost.find(params[:id])
    respond_to do |format|
      format.js{ render "streams/ajax/ajax_load_likes" }
    end
  end

  def ajax_load_comments
    @post = WallPost.find(params[:post_id])
    @comments = @post.comments.all(:include => {:user => :photo},
                                    :limit => Constants::WallCommentsPerPage,
                                    :offset => (params["page"].to_i * Constants::WallCommentsPerPage),
                                    :order => "created_at ASC")
    if @comments.size > 0
      respond_to do |format|
        format.js{ render "streams/ajax/ajax_load_comments" }
      end
      return
    end
    render :text => ""
  end

  def ajax_delete_post
    @post = WallPost.find(params[:id])
    if !@post.nil?
      @post_id = @post.id
      if [@post.user, @post.poster_user].include? @user
        @post.delete_post
        respond_to do |format|
          format.js{ render "streams/ajax/ajax_delete_post" }
        end
        return
      end
    end
    render :text => ""
  end


  private

  def get_wall_configs
    wall_pinnings = @user.wall_pinnings.all(:include => {:pinned_user => [:wall_posts, :photo]}, :order => "slot ASC")

    @wall_configs = []
    wall_pinnings.each do | wp |
      @wall_configs << WallConfig.new({:pinning => wp, :on_your_page => true })
    end
  end
end

app/views/streams/_hang_a_friend.html.erb
<div class="header">
  <h5 style="margin: 5px 0px;">Pin a Friend's Stream</h5>
  <%= text_field_tag "find_friend", {}, { :placeholder => "Enter first name, last name, or email..." } %>
</div>

<div class="hang_a_friend">
  <%= form_for @wall_pinning, :url => streams_pin_user_url, :html => { :id => "request_friend_form" } do | f | %>
    <div class="found_friend" id="found_friend"></div>
    <%= f.hidden_field :pinned_user_id %>
    <%= f.submit "Pin", :class => "button small", :disabled => true %>
  <% end %>
</div>

<% content_for :javascripts do %>
  <script type="text/javascript">
  $(document).ready(function(){
    $( "#find_friend" ).autocomplete({
      minLength: 2,
      source: "/users/ajax_find_friend",
      select: Groovesy.FriendSelected
    });
  });
  </script>
<% end %>

app/views/streams/_post.html.erb
<div id="post" data-id="<%= post.id %>" class="post clearfix" post-date="<%= post.created_at %>">

  <%= render :partial => "shared/post_header", :locals => { :post => post, :render_context => render_context } %>

  <div class="by_line">
    <%= render :partial => "shared/by_line", :locals => { :post => post, :show_dest => show_dest } %>
  </div>

  <%= raw process_post_text( post, "small", !@user.nil?) if Constants::ShowPosts %>

  <%= render :partial => "shared/attribution", :locals => { :post => post } if Constants::Providers.include?(post.api_provider) %>

  <div class="likes">
    <span class="like_count" data-id="<%= post.id %>">
      <%= render :partial => "shared/likes", :locals => { :post => post, :linkify => true } %>
    </span>

    <% if !@user.nil? %>
      <%= link_to "Like", streams_ajax_like_url(post), :remote => true %>
    <% end %>
  </div>

  <div class="comments">

    <% comments = post.comments.all(:limit => Constants::WallCommentsPerPage, :offset => 0) %>

    <ul data-id="<%= post.id %>" class="current_comments">
      <% comments.each do | comment | %>
        <%= render :partial => "shared/comment", :locals => { :comment => comment } %>
      <% end %>
    </ul>

    <% if !@user.nil? %>
      <div class="add_comment clearfix">
        <%= link_to "Add Comment", "javascript: void(0);", :class => "add_comment_link right", "data-id" => post.id %>
      </div>
    <% end %>

    <%= form_for :wall_post_comment, :url => streams_ajax_comment_url(post), :remote => true, :html => {"data-id" => post.id, :class => "wall_post_comment_form", :style => "display: none;" } do | f | %>
      <%= hidden_field_tag :page %>
      <%= hidden_field_tag :render_context, render_context %>
      <%= f.text_area :comment, :rows => 2 %>
      <%= f.submit "Post", :class => "small button right" %>
    <% end %>

    <% if post.comments.count > Constants::WallCommentsPerPage %>
      <div data-id="<%= post.id %>" class="show_more_comments more"><%= image_tag("downarrow.png") %></div>

      <% content_for :javascripts do %>
        <script type="text/javascript">
        $(function() {
          $("body").find("[data-id='<%= post.id %>'] .show_more_comments").bind("click", function(){
            Groovesy.ShowMoreComments(<%= post.id %>, "/streams/ajax_load_comments", "<%= render_context %>");
          });
        });
        </script>
      <% end %>
    <% end %>

  </div>
</div>

app/views/streams/_repin_form.html.erb
<h5 style="margin: 0px 0px 5px 0px;" class="left">Repin Post</h5>

<%= link_to image_tag("x_button_light.png"), "javascript: void(0);", :id => "repin_form_close_btn", :class => "right" %>

<%= form_for @new_post, :url => streams_ajax_post_repin_url, :remote => true do | f | %>
  <%= hidden_field_tag :repin_content, @new_post.repin_content %>

  <%= f.text_area :post_text, :value => "", :placeholder => "Enter comments...", :rows => 2 %>

  <div class="repinned_content">
    <%= raw process_post_text( @new_post, "small", !@user.nil? ) %>
  </div>

  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :poster_user_id %>
  <%= f.hidden_field :repin_parent_id %>

  <%= f.submit "Repin", :class => "small button right", :style => "margin-top: 5px;" %>
<% end %>

app/views/streams/_stream.html.erb
<% user = wall_config.pinning.pinned_user %>

<div class="header clearfix">

  <% if !@user.nil? && wall_config.pinning.pinned_user == @user %>
    <%= render_profile_photo( user, "64x64" ) %>
    My Stream<br />
  <% else %>
    <%= link_to profile_user_url(user) do %><%= render_profile_photo( user, "64x64", "profile-photo" ) %><% end %>

    <% if wall_config.on_your_page %>
      <%= link_to image_tag("x_button_light.png"), streams_ajax_unpin_user_url(wall_config.pinning), { :remote => true, :confirm => "Are you sure you want to unpin this friend?", :class  => "unpin" } %>
    <% end %>

    <%= link_to user.first_and_last_name, profile_user_url(user) %><br />
  <% end %>

  <%= render_friend_count(user) %><br />
  <%= pluralize user.posted_posts.count, "Post" %>
</div>

<%= render :partial => "streams/stream_body", :locals => { :wall_pinning => wall_config.pinning } %>

app/views/streams/_stream_body.html.erb
<div class="stream-content" data-id="<%= wall_pinning.id %>">

  <% if !@user.nil? %>
    <div class="stream-post" style="position: relative;">

      <%= form_for @wall_post, :url => streams_ajax_post_url, :remote => true, :class => "custom" do |f| %>
        <div class="input_box_mask" data-id="<%= wall_pinning.id %>"><%= image_tag "ajax-loader.gif", :style => "left: 100px;" %></div>
        <%= hidden_field_tag :wall_pinning_id, wall_pinning.id %>
        <%= f.text_area :post_text, :class => "wall_input_box", :rows => 2, "data-id" => wall_pinning.id, :placeholder => "Enter SoundCloud, YouTube, MixCloud, or Image url..." %>
        <%= f.hidden_field :user_id, :value => wall_pinning.pinned_user_id %>

        <div id="post_preview_<%= wall_pinning.id %>" class="post_preview">
          <div id="preview_ajax_loader_<%= wall_pinning.id %>" style="display: none;">Loading Track Details...<%= image_tag "ajax-loader.gif" %></div>
          <div class="small-media-container" id="post_preview_media_container_<%= wall_pinning.id %>"></div>
          <%= link_to image_tag("x_button_light.png", :alt => ""), "javascript: void(0);", { "data-id" => wall_pinning.id, :class => "post_preview_close_button", :style => "position: absolute; right: 5px; top: 5px;" } %>
        </div>

        <div class="post_bar_small small clearfix">
          <%= f.submit "Post", :class => "button post small", "data-id" => wall_pinning.id, :style => "float: right;" %>
        </div>
      <% end %>
    </div>

    <%= render :partial => "shared/provider_preview_templates" %>
  <% end %>

  <div class="stream_posts" data-id="<%= wall_pinning.id %>">
    <% posts = wall_pinning.pinned_user.recent_wall_posts(0, Constants::WallPostsPerPage) %>

    <% posts.each do | post | %>
      <%= render :partial => "streams/post", :locals => { :post => post,
                                                          :context => "user_wall",
                                                          :render_context => "stream",
                                                          :show_dest => wall_pinning.pinned_user_id != post.user_id } %>
    <% end %>

    <% if wall_pinning.pinned_user.recent_wall_posts.size > Constants::WallPostsPerPage %>
      <div data-id="<%= wall_pinning.id %>" class="show_more_posts more"><%= image_tag("downarrow.png") %></div>
    <% end %>
  </div>
</div>

<% content_for :javascripts do %>

  <script type="text/javascript">
    $(function() {
      $("body").find("[data-id='<%= wall_pinning.id %>'] .show_more_posts").bind("click", function() {
        Groovesy.ShowMorePosts(<%= wall_pinning.id %>);
      });
    });

    <% posts.each do | post | %>
    var current_comments_page_<%= post.id %> = 0;
    <% end %>

  </script>

<% end %>

app/views/streams/index.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Streams<% end %>

<script type="text/javascript">
  var current_page = new Array();
  <% @wall_configs.each do | wc | %>
    var current_page_<%= wc.pinning.id %> = 0;
  <% end %>
</script>

<%= raw render_flash( flash ) %>

<h1>Streams</h1>

<p>Streams let you view what your favorite friends are listening to.</p>

<div class="show-for-touch panel callout">Use two fingers to scroll &#187;</div>

<div class="mega-width">
  <% @wall_configs.each do | wc | %>
    <% if !wc.pinning.pinned_user_id.nil? %>
      <div class="stream left" id="friend<%= wc.pinning.id %>_wall">
        <%= render :partial => "streams/stream", :locals => { :wall_config => wc } %>
      </div>
    <% end %>
  <% end %>

  <div class="stream left" id="friend_new_wall">
    <%= render :partial => "streams/hang_a_friend" %>
  </div>
</div>

<%= render :partial => "shared/likes_hide" %>

<% content_for :javascripts do %>
  <script type="text/javascript">
  $(document).ready(function() {
    Groovesy.MakeColorbox();
  });
  </script>
<% end %>