config/routes.rb
Earful::Application.routes.draw do

  root :to => "content#index"

  match '/wall/ajax_load_post_details' => "wall#ajax_load_post_details"
  match '/wall/public/ajax_subscribe/:id' => "wall#ajax_subscribe", :as => :wall_ajax_subscribe
  match '/wall/public/ajax_unsubscribe/:id' => "wall#ajax_unsubscribe", :as => :wall_ajax_unsubscribe
  match '/wall/unsubscribe/:id' => "wall#unsubscribe", :as => :wall_unsubscribe
  match '/wall/search/:tag' => "wall#search", :as => :wall_search
  match '/wall/public/ajax_post' => "wall#ajax_public_post", :as => :wall_ajax_public_post
  match '/wall/ajax_post' => "wall#ajax_post", :as => :wall_ajax_post

  match '/streams/ajax_post' => "streams#ajax_post", :as => :streams_ajax_post
  match '/streams/pin_user' => "streams#pin_user", :as => :streams_pin_user
  match '/streams/ajax_unpin_user/:id' => "streams#ajax_unpin_user", :as => :streams_ajax_unpin_user
  match '/streams/ajax_load_posts' => "streams#ajax_load_posts", :as => :streams_ajax_load_posts
  match '/streams/like/:id' => "streams#ajax_like", :as => :streams_ajax_like
  match '/streams/repin/:id' => "streams#ajax_repin", :as => :streams_repin
  match '/streams/ajax_post_repin' => "streams#ajax_post_repin", :as => :streams_ajax_post_repin
  match '/streams/ajax_load_likes/:id' => "streams#ajax_load_likes", :as => :streams_ajax_load_likes
  match '/streams/comment/:id' => "streams#ajax_comment", :as => :streams_ajax_comment
  match '/streams/ajax_load_comments' => "streams#ajax_load_comments"
  match '/streams/ajax_delete_post/:id' => "streams#ajax_delete_post", :as => :streams_ajax_delete_post

  match '/content/ajax_load_comments' => "content#ajax_load_comments", :as => :content_ajax_load_comments
  match '/content/comment/:id' => "content#ajax_comment", :as => :content_ajax_comment
  match '/privacy-policy' => "content#privacy_policy"

  resources :users do
    member do
      get "wall", "fb_connect", "profile"
    end

    collection do
      get "ajax_find_friend", "invite"
      post "send_invitation", "fb_register"
    end
  end

  resources :posts

  resources :notifications do
    collection do
      get "ajax_load"
      post "ajax_ack"
    end
  end

  resources :login do
    collection do
      get "fb_login", "retrieve_password", "reset_password"
      post "mail_guid", "save_password"
    end
  end

  resources :wall, :except => :show do
    collection do
      get "my_walls", "friends", "my_likes"
    end
  end

  resources :streams, :except => :show

  match '/wall/:slug' => "wall#view", :as => :view_wall

  resources :friends do
    collection do
      get "find"
      post "search"
    end
  end

  match '/friend_requests/' => "friend_requests#index", :as => :friend_requests_index
  match '/friend_requests/update/:id/:status' => "friend_requests#update", :as => :friend_requests_update
  match '/friend_requests/new/:id' => "friend_requests#new", :as => :new_friend_requests
  match '/friend_requests/:id/ajax_new' => "friend_requests#ajax_new", :as => :ajax_new_friend_requests

  match '/email/unsubscribe/:key' => "email_unsubscribe#index", :as => :email_unsubscribe
  match '/facebook/invited' => "content#facebook_invited"
  match '/facebook' => "content#facebook_app"
end

app/views/shared/_attribution.html.erb
<div class="site_attribution">
  Source: <%= render :partial => "shared/provider_attributions/#{post.api_provider.downcase}", :locals => { :post => post } %>
</div>

app/views/shared/_comment.html.erb
<li data-id="<%= comment.id %>">
  <div class="by_line">
    <%= link_to profile_user_url(comment.user) do %><%= render_profile_photo( comment.user, "32x32" ) %><% end %>
    <%= link_to comment.user.first_and_last_name, profile_user_url(comment.user) %> <%= custom_time_ago_in_words(comment.created_at) %> wrote:
  </div>
  <%= raw dotted_linkify comment.comment %>
</li>

app/views/shared/_discover_nub.html.erb
<% if @user.nil? %>
  <div class="row">
    <div class="eight columns centered">
      <div class="panel radius">
        <div class="row">
          <div class="six columns" style="font-size: 1.8em;">
            Groovesy lets you share Youtube, SoundCloud, and MixCloud tracks with friends.
          </div>

          <div class="three columns">
            <%= link_to "Join Groovesy", new_user_url(), :class => "button" %>
          </div>
          <div class="three columns">
            <%= link_to "Login", login_index_url(), :class => "button secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_fb_like_code.html.erb
<div id="fb-root"></div>

<script type="text/javascript">
  window.fbAsyncInit = function() {
    FB.init({appId: '<%= Rails.configuration.FacebookAppId %>', status: true, cookie: true, xfbml: true, oauth: true});
  };

  // Load the SDK Asynchronously
  (function(d){
    var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement('script'); js.id = id; js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js";
    ref.parentNode.insertBefore(js, ref);
  }(document));
</script>

app/views/shared/_fb_share_button.html.erb
<% img_tag = image_tag("fb_share_button.jpg", :align => "absmiddle") %>
<% if type == :post %>
  <% if @wall_post.is_video %>
    <%= link_to_function img_tag, "Groovesy.FBRichShare('#{escape_single_quotes(@wall_post.meta_title)}', '#{link}', '#{ @wall_post.thumbnail_url }', '#{ @player_url }', '#{format_fb_share_desc(@wall_post.description)}')" %>
  <% elsif @wall_post.api_provider == "Unknown" %>
    <%= link_to_function img_tag, "Groovesy.FBShare('A post on Groovesy.com', '#{link}', '#{format_fb_share_desc(@wall_post.post_text)}')" %>
  <% else %>
    <%= link_to_function img_tag, "Groovesy.FBRichShare('A photo on Groovesy.com', '#{link}', '#{ @wall_post.thumbnail_url }', '#{ @player_url }', '#{format_fb_share_desc(@wall_post.post_text)}')" %>
  <% end %>
<% else %>
  <%= link_to_function img_tag, "Groovesy.FBShare('#{wall.name} Wall on Groovesy.com', '#{view_wall_url(wall.slug)}', '#{format_fb_share_desc(wall.description)}')" %>
<% end %>

app/views/shared/_find_friends_buttons.html.erb
<%= link_to_function image_tag("fb_invite_button.png"), "Groovesy.SendFBAppRequestViaMultiFriendSelector()", :id => "fb_invite_lnk", :class => "right" %>
<%= button_to "Invite a Friend", invite_users_url, :method => :get, :class => "small button right" %>
<%= button_to "Search For Friends on Groovesy", find_friends_url, :method => :get, :class => "small button right" %>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29179804-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/shared/_header.html.erb
<%= render :partial => "shared/logo" %>
<%= render :partial => "layouts/nav" %>
<%= render :partial => "shared/discover_nub" %>

app/views/shared/_javascripts.html.erb
<%= javascript_include_tag 'application' %>
<%= yield :javascripts_after_jquery %>
<%= yield :javascripts %>

<% if !@user.nil? %>
  <script type="text/javascript">
  $(document).ready(function()
  {
    $('#notifications_list').hover(function(){
      notif_mouse_is_inside = true;
    }, function(){
      notif_mouse_is_inside = false;
    });

    $("body").mouseup(function(){
      if(!notif_mouse_is_inside){
        $("#notifications_list").fadeOut("slow");
      }
    });
  });
  </script>
<% end %>

app/views/shared/_likes.html.erb
<% likes = post.likes.count %>

<% if likes > 0 && linkify %>
  <%= link_to(streams_ajax_load_likes_url(post), :remote => true) do %><%= likes %> <%= likes == 0 || likes > 1 ? "People" : "Person" %><% end %>
<% else %>
  <%= likes %> <%= likes == 0 || likes > 1 ? "People" : "Person" %>
<% end %>

<%= likes == 0 || likes > 1 ? "Like" : "Likes" %> This

app/views/shared/_likes_hide.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
  $(document).ready(function()
  {
    $(document).mouseup(function (e)
    {
      var container = $("#likes_list");

      if (container.has(e.target).length === 0)
      {
        container.hide();
      }
    });

    $("body").bind( "touchend", function(e) {
      var container = $("#likes_list");

      if (container.has(e.target).length === 0)
      {
        container.hide();
      }
    });
  });
  </script>
<% end %>

app/views/shared/_post_header.html.erb
<div id="post_header_<%= post.id %>" class="post_header">
  <% if !@user.nil? %>
    <% if [post.user, post.poster_user].include? @user %>
      <%= link_to image_tag("x_button_light.png", :alt => "", :align => "absmiddle"), streams_ajax_delete_post_url(post) + "?render_context=#{render_context}", { :remote => true, :confirm => "Are you sure you want to delete this post?", :class => "right" } %>
    <% else %>
      <%= link_to image_tag('pin_icon.jpg'), streams_repin_url(post), :remote => true, :class => "right" %>
    <% end %>
  <% end %>

  <%= "#{pluralize(WallPost.repins(post).count, 'Repin')}" %>
</div>

app/views/shared/_provider_preview_templates.html.erb
<!-- Provider Preview Templates -->
<script id="mixcloud_tmpl" type="text/x-jquery-tmpl">
  <div class="row">
    <div class="five columns">
      <a href="${url}" target="_blank"><img src='${thumbnail_url}' /></a>
    </div>
    <div class="seven columns">
      <a href="${url}" target="_blank">${title}</a><br />
      by ${artist}<br />
      www.${provider}.com
    </div>
  </div>
</script>

<script id="soundcloud_tmpl" type="text/x-jquery-tmpl">
  <div class="row">
    <div class="five columns">
      <a href="${url}" target="_blank"><img src='${thumbnail_url}' /></a>
    </div>
    <div class="seven columns">
      <a href="${url}" target="_blank">${title}</a><br />
      by ${artist}<br />
      www.${provider}.com
    </div>
  </div>
</script>

<script id="image_tmpl" type="text/x-jquery-tmpl">
  <a href='${url}' target="_blank"><img src='${url}' border='0' width='120'/></a>
</script>

<script id="youtube_tmpl" type="text/x-jquery-tmpl">
  <div class="row">
    <div class="five columns">
      <a href="${url}" target="_blank"><img src='${thumbnail_url}' /></a>
    </div>
    <div class="seven columns">
      <a href="${url}" target="_blank">${title}</a><br />
      by ${artist}<br />
      www.${provider}.com
    </div>
  </div>
</script>

app/views/shared/_site_meta.html.erb
<meta property="og:title" content="Groovesy - All the best tracks" />
<meta property="og:type" content="website" />
<meta property="og:description" content="Groovesy lets you discover and share the best tracks." />
<meta property="og:url" content="http://www.groovesy.com" />
<meta property="og:image" content="http://www.groovesy.com/images/logo.jpg" />
<meta property="og:site_name" content="Groovesy.com" />
<meta property="fb:admins" content="514751105" />
<meta property="fb:app_id" content="301114093284321" />