config/routes.rb
Earful::Application.routes.draw do

  root :to => "content#index"

  match '/wall/ajax_load_post_details' => "wall#ajax_load_post_details"
  match '/wall/public/ajax_subscribe/:id' => "wall#ajax_subscribe", :as => :wall_ajax_subscribe
  match '/wall/public/ajax_unsubscribe/:id' => "wall#ajax_unsubscribe", :as => :wall_ajax_unsubscribe
  match '/wall/unsubscribe/:id' => "wall#unsubscribe", :as => :wall_unsubscribe
  match '/wall/search/:tag' => "wall#search", :as => :wall_search
  match '/wall/public/ajax_post' => "wall#ajax_public_post", :as => :wall_ajax_public_post
  match '/wall/ajax_post' => "wall#ajax_post", :as => :wall_ajax_post

  match '/streams/ajax_post' => "streams#ajax_post", :as => :streams_ajax_post
  match '/streams/pin_user' => "streams#pin_user", :as => :streams_pin_user
  match '/streams/ajax_unpin_user/:id' => "streams#ajax_unpin_user", :as => :streams_ajax_unpin_user
  match '/streams/ajax_load_posts' => "streams#ajax_load_posts", :as => :streams_ajax_load_posts
  match '/streams/like/:id' => "streams#ajax_like", :as => :streams_ajax_like
  match '/streams/repin/:id' => "streams#ajax_repin", :as => :streams_repin
  match '/streams/ajax_post_repin' => "streams#ajax_post_repin", :as => :streams_ajax_post_repin
  match '/streams/ajax_load_likes/:id' => "streams#ajax_load_likes", :as => :streams_ajax_load_likes
  match '/streams/comment/:id' => "streams#ajax_comment", :as => :streams_ajax_comment
  match '/streams/ajax_load_comments' => "streams#ajax_load_comments"
  match '/streams/ajax_delete_post/:id' => "streams#ajax_delete_post", :as => :streams_ajax_delete_post

  match '/content/ajax_load_comments' => "content#ajax_load_comments", :as => :content_ajax_load_comments
  match '/content/comment/:id' => "content#ajax_comment", :as => :content_ajax_comment
  match '/privacy-policy' => "content#privacy_policy"

  resources :users do
    member do
      get "wall", "fb_connect", "profile"
    end

    collection do
      get "ajax_find_friend", "invite"
      post "send_invitation", "fb_register"
    end
  end

  resources :posts

  resources :notifications do
    collection do
      get "ajax_load"
      post "ajax_ack"
    end
  end

  resources :login do
    collection do
      get "fb_login", "retrieve_password", "reset_password"
      post "mail_guid", "save_password"
    end
  end

  resources :wall, :except => :show do
    collection do
      get "my_walls", "friends", "my_likes"
    end
  end

  resources :streams, :except => :show

  match '/wall/:slug' => "wall#view", :as => :view_wall

  resources :friends do
    collection do
      get "find"
      post "search"
    end
  end

  match '/friend_requests/' => "friend_requests#index", :as => :friend_requests_index
  match '/friend_requests/update/:id/:status' => "friend_requests#update", :as => :friend_requests_update
  match '/friend_requests/new/:id' => "friend_requests#new", :as => :new_friend_requests
  match '/friend_requests/:id/ajax_new' => "friend_requests#ajax_new", :as => :ajax_new_friend_requests

  match '/email/unsubscribe/:key' => "email_unsubscribe#index", :as => :email_unsubscribe
  match '/facebook/invited' => "content#facebook_invited"
  match '/facebook' => "content#facebook_app"
end

app/models/wall.rb
class Wall < ActiveRecord::Base
  belongs_to :admin, :class_name => "User", :foreign_key => "admin_id"
  has_many :wall_members
  has_many :wall_users, :through => :wall_members
  has_many :posts, :class_name => "WallPost", :foreign_key => "wall_id", :conditions => "post_type='public_wall'"

  validates_presence_of [:name, :admin_id], :message => "is required"
  validates_presence_of :slug, :message => "is required", :if => Proc.new{|slf| !slf.name.blank? }
  validates_uniqueness_of :slug, :message => "is already taken"
  validates_length_of [:tags, :name], :maximum => 255

  def set_slug
    self.slug = Util.get_slug(self.name)
    x = 1
    while(!Wall.find_by_slug(self.slug).nil?) do # scary, but I think this will work
      self.slug = "#{Util.get_slug(self.name)}-#{x}"
      x += 1
    end
  end

  def self.random_walls
    Wall.all(:limit => Constants::MaxRandomWallsMyWallsPage, :order => "RAND()")
  end

  def self.search(tag)
    Wall.all(:conditions => ["tags LIKE ?", "%" + tag + "%"])
  end
end

app/controllers/wall_controller.rb
class WallController < ApplicationController
  layout "application"
  before_filter :init, :except => [:view]
  helper :wall

  def init
    @active_tab = "walls"
    if @user.nil?
      redirect_to login_index_url
    end
  end

  def index
    @wall_post = WallPost.new
    @posts = @user.posts
    render :layout => "full_page_isotope"
  end

  def friends
    @posts = @user.friend_posts
    render :layout => "full_page_isotope"
  end

  def my_likes
    @posts = @user.likes
    render :layout => "full_page_isotope"
  end

  def new
    @wall = Wall.new
  end

  def create
    @wall = Wall.new(params[:wall])
    @wall.set_slug
    @wall.admin_id = @user.id
    if @wall.valid?
      @wall.save
      @user.join_wall(@wall)
      @posts = @wall.posts.all(:include => [:likes, {:comments => {:user => :photo}}], :order => "created_at DESC", :limit => Constants::MaxPostsPublicWall)
      @wall_post = WallPost.new(:wall_id => @wall.id)
      @user.reload
      flash.now[:notice] = "Your wall has been created, and you are the admin."
      render :template => "wall/view", :layout => "wall_with_right_sidebar"
    else
      flash.now[:error] = Util.errors_with_markup( @wall.errors )
      render :template => "wall/new"
    end
  end

  def edit
    @wall = Wall.find(params[:id])
  end

  def update
    @wall = Wall.find(params[:id])
    @wall.attributes = params[:wall]
    @wall.set_slug
    if @wall.valid?
      @wall.save
      flash[:notice] = "The wall has been updated."
      redirect_to view_wall_url(@wall.slug)
    else
      flash.now[:error] = Util.errors_with_markup( @wall.errors )
      render :template => "wall/edit"
    end
  end

  def view
    @active_tab = "walls"
    @wall = Wall.first(:conditions => ["slug = ?", params[:slug]])
    @wall_post = WallPost.new(:wall_id => @wall.id)
    @posts = @wall.posts.all(:include => [:likes, {:comments => {:user => :photo}}], :order => "created_at DESC", :limit => Constants::MaxPostsPublicWall)
    render :layout => "wall_with_right_sidebar"
  end

  def destroy
    @wall = Wall.find_by_id_and_admin_id(params[:id], @user.id)
    if !@wall.nil?
      @wall.posts.each{ | p | p.delete_post }
      @wall.wall_members.each{ |wm| wm.destroy }
      @wall.destroy
      @walls = @user.admin_walls
      @random_walls = Wall.random_walls
      render :template => "wall/my_walls"
      return
    end
    render :text => ""
  end

  def search
    @walls = Wall.search(params[:tag])
  end

  def my_walls
    @walls = @user.admin_walls
    @random_walls = Wall.random_walls
    render :layout => "full_page"
  end

  def unsubscribe
    @wall = Wall.find(params[:id])
    if @user.member_of?(@wall)
      @user.leave_wall(@wall)
      flash.now[:notice] = "You are unsubscribed from #{@wall.name}"
    else
      flash.now[:error] = "You are not subscribed to #{@wall.name}"
    end
    @user.reload
    @walls = @user.admin_walls
    @random_walls = Wall.random_walls
    render :template => "wall/my_walls"
  end

  def ajax_subscribe
    @wall = Wall.find(params[:id])
    if !@user.member_of?(@wall)
      @user.join_wall(@wall)
      respond_to do |format|
        format.js{ render "wall/ajax/ajax_subscribe" }
      end
      return
    end
    render :text => ""
  end

  def ajax_unsubscribe
    @wall = Wall.find(params[:id])
    if @user.member_of?(@wall)
      @user.leave_wall(@wall)
      respond_to do |format|
        format.js{ render "wall/ajax/ajax_unsubscribe" }
      end
      return
    end
    render :text => ""
  end

  def ajax_post
    @wall_post = WallPost.new(params[:wall_post])
    @wall_post.post_type = "user_wall"
    @wall_post.user = @user
    @wall_post.poster_user = @user
    Util.strip_html(@wall_post.post_text)
    if @wall_post.valid?
      @wall_post.get_track_details
      @wall_post.save
      respond_to do |format|
        format.js{ render "wall/ajax/ajax_post" }
      end
    else
      render :text => ""
    end
  end

  def ajax_public_post
    @wall_post = WallPost.new(params[:wall_post])
    @wall_post.post_type = "public_wall"
    @wall_post.poster_user = @user
    Util.strip_html(@wall_post.post_text)
    if @wall_post.valid?
      @wall_post.get_track_details
      @wall_post.save
      @wall_post.wall.wall_users.each do | u |
        if u != @user && Constants::DeliverMail && EmailUnsubscribe.find_by_email_and_set(u.email, true).nil?
          UserMailer.deliver_public_wall_post_notification( u, @wall_post.wall, @user, @wall_post )
        end
      end
      respond_to do |format|
        format.js{ render "wall/ajax/public/ajax_post" }
      end
    else
      render :text => ""
    end
  end

  def ajax_load_post_details
    wall_post = WallPost.new({:post_text => params['post_text']})
    wall_post.get_track_details

    respond_to do |format|
      format.json { render :json => wall_post.preview_json }
    end
  end
end

app/helpers/wall_helper.rb
module WallHelper
  def render_new_fr_count(user)
    count = user.new_friends.size + user.friend_requests.size
    
    return "<span id='fr_count'>+#{ count }</span>" if count > 0
    return ""
  end

  def render_tags(tags)
    result = ""
    if tags.blank?
      return "No tags yet"
    end
    tags.split(",").each_with_index do | tag, index |
      tag.strip!
      result += link_to(tag, wall_search_url(tag)) + ( index < tags.split(",").size - 1  ? "|" : "" )
    end
    result
  end
end

app/views/wall/_form.html.erb
<label for="wall_name">*Name (Example: "Dallas Electronic Music Wall")</label>
<%= f.text_field :name %>

<label for="wall_description">Description</label>
<%= f.text_area :description, :rows => 4 %>

<label for="wall_tags">Tags (Example: dallas, electronic)</label>
<%= f.text_field :tags %>

<%= f.submit "Submit", :class => "button" %>

app/views/wall/_input_box.html.erb
<% if !@user.nil? %>
  <div class="row">
    <div class="<%= columns %> columns centered">

      <div class="panel post-box" style="padding: 10px; position: relative; margin-bottom: 10px;">
        <div class="input_box_mask" data-id="single"><%= image_tag "ajax-loader.gif", :style => "left: 138px;" %></div>

        <%= form_for @wall_post, :url => post_url, :html => { :remote => true } do | f | %>

          <div class="row">
            <div class="twelve columns">
              <h4><%= header_text %></h4>
              <%= f.text_area :post_text, :cols => 20, :rows => 2, :class => "public_wall_input_box", "data-id" => "single", :placeholder => "Enter SoundCloud, YouTube, MixCloud, or Image url..." %>
              <%= f.hidden_field :wall_id %>
            </div>
          </div>

          <div id="post_preview_single" class="row post_preview">
            <div class="twelve columns">
              <div style="padding: 5px 0px 5px 0px; border-top: 1px dashed #ccc; position: relative;">
                <div id="preview_ajax_loader_single" style="display: none;">Loading Track Details...<%= image_tag "ajax-loader.gif" %></div>
                <div id="post_preview_media_container_single"></div>
                <%= link_to image_tag("x_button_light.png", :alt => ""), "javascript: void(0);", { "data-id" => "single", :class => "post_preview_close_button", :style => "position: absolute; right: 5px; top: 5px;" } %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="twelve columns">
              <div class="post_bar">
                <%= f.submit "Post", :class => "post button", "data-id" => "single" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <%= render :partial => "shared/provider_preview_templates" %>
<% end %>

app/views/wall/_posts.html.erb
<div id="posts_container" class="clearfix">
  <% @posts.each do | post | %>
      <%= render :partial => "streams/post", :locals => { :post => post,
                                                          :context => "user_wall",
                                                          :render_context => "isotope",
                                                          :show_dest => true } %>
  <% end %>
</div>

<%= render :partial => "shared/likes_hide" %>

<% content_for :javascripts do %>
  <script type="text/javascript">
    <% @posts.each do | post | %>
    var current_comments_page_<%= post.id %> = 0;
    <% end %>
  </script>
<% end %>

app/views/wall/edit.html.erb
<% content_for :title do %>
  <%= Constants::SiteName %> - Edit Wall
<% end %>

<div class="row">
  <div class="ten columns centered">
    <h1>Edit Wall</h1>

    <%= raw render_flash( flash ) %>

    <%= form_for( @wall, :url => wall_url(@wall), :html => { :class => "custom" } ) do | f | %>
      <%= render :partial => "form", :locals => { :f => f } %>
    <% end %>
  </div>
</div>

app/views/wall/friends.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Your Friends<% end %>

<h1>My Friends' Posts</h1>

<% if @user.confirmed_friends.size == 0 || @posts.size == 0 %>
  Your friends haven't posted anything yet.
  <%= link_to_function image_tag("fb_invite_button.png", :align => "absmiddle"), "Groovesy.SendFBAppRequestViaMultiFriendSelector()" %>
<% else %>
  <%= render :partial => "posts" %>
<% end %>

app/views/wall/index.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Your Wall<% end %>

<%= raw render_flash( flash ) %>

<%= render :partial => "wall/input_box", :locals => { :wall_user => @user, :post_url => wall_ajax_post_url, :header_text => "Post to Your Wall", :columns => "five" } %>

<%= render :partial => "wall/posts" %>

app/views/wall/my_likes.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Your Likes<% end %>

<h1>My Likes</h1>

<% if @posts.size == 0 %>
  No likes yet.
<% else %>
  <%= render :partial => "posts" %>
<% end %>

app/views/wall/my_walls.html.erb
<div class="row">
  <div class="five columns">
    <h1>Walls I've Created</h1>
    <% if !@walls.empty? %>
      <table class="walls" width="100%">
        <thead>
          <tr>
            <th>Name</th>
            <th>Members</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
        <% @walls.each do | w | %>
          <tr>
            <td><%= link_to w.name, view_wall_url(w.slug) %></td>
            <td><%= w.wall_users.size %></td>
            <td><%= link_to "Edit", edit_wall_url(w) %></td>
            <td><%= link_to "Delete Wall", wall_url(w), :method => :delete, :confirm => "Are you sure you want to remove this wall?  This will remove all posts and comments." %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>You have not created any custom walls.</p>
    <% end %>
    <%= button_to "Create a Custom Wall", new_wall_url, :class => "button", :method => :get %>
  </div>


  <div class="six columns offset-by-one">
    <h1>Wall Subscriptions</h1>
    <% if !@user.member_walls.empty? %>
      <table class="walls" width="100%">
        <thead>
        <tr>
          <th>Name</th>
          <th>Members</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @user.member_walls.each do | w | %>
          <tr>
            <td><%= link_to w.name, view_wall_url(w.slug) %></td>
            <td><%= w.wall_users.size %></td>
            <td><%= link_to "Unsubscribe", wall_unsubscribe_url(w), :confirm => "Are you sure you want to unsubscribe from this wall?" %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Wall subscriptions allow you to follow updates to walls.  Keep up with what's going on with your favorite
        band, city, or venue.
      </p>
      <p><em>You are not subscribed to any walls.  To subscribe, visit a wall and click Subscribe.</em></p>
    <% end %>


    <h1>Walls to Subscribe To</h1>
    <% if !@random_walls.empty? %>
      <table width="100%">
        <thead>
        <tr>
          <th>Name</th>
          <th>Tags</th>
        </tr>
        </thead>

        <tbody>
        <% @random_walls.each do | w | %>
          <tr>
            <td><%= link_to w.name, view_wall_url(w.slug) %></td>
            <td><%= raw render_tags(w.tags) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Wow, there are no walls yet.  Be the first to <%= link_to "Create One", new_wall_url %>.</p>
    <% end %>
  </div>
</div>

app/views/wall/new.html.erb
<% content_for :title do %>
  <%= Constants::SiteName %> - Create a Custom Wall
<% end %>

<div class="page_form clearfix">
  <h1>Create a Custom Wall</h1>

  <p style="margin-bottom: 20px;">Got a band?  Live in a cool city?  Love Hardcore?  Be one of the first people to start a wall to promote your favorite music.</p>

  <%= raw render_flash( flash ) %>

  <%= form_for( @wall, :url => wall_index_url, :html => { :class => "new_wall" } ) do | f | %>
    <%= render :partial => "form", :locals => { :f => f } %>
  <% end %>
</div>

app/views/wall/search.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Walls Tagged "<%= params[:tag] %>"<% end %>

<h1>Walls tagged: "<%= params[:tag] %>"</h1>
<% if !@walls.empty? %>
  <table width="100%" class="wall-search-list">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Tags</th>
        <th align="center">Members</th>
      </tr>
    </thead>

    <tbody>
      <% @walls.each do | w | %>
        <tr>
          <td><%= link_to w.name, view_wall_url(w.slug) %></td>
          <td><%= w.description.size > 75 ? w.description[0..75] + "..." : w.description %></td>
          <td><%= raw render_tags(w.tags) %></td>
          <td align="center"><%= w.wall_users.size %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No walls match the tag you entered
<% end %>

app/views/wall/view.html.erb
<% content_for :title do %><%= Constants::SiteName %> - Wall - <%= @wall.name %><% end %>
<% content_for :description do %><%= @wall.description %>.<% end %>

<%= raw render_flash( flash ) %>

<div class="row groovesy-panel" style="margin: 0px;">

  <div class="three columns" style="padding: 10px;">

    <div class="row">
      <div class="three columns">
        Tags:
      </div>
      <div class="nine columns">
        <%= raw render_tags(@wall.tags) %>
      </div>
    </div>

    <div class="row" style="margin-top: 8px;">
      <div class="three columns">
        Admin:
      </div>
      <div class="nine columns">
        <%= link_to @wall.admin.first_and_last_name, profile_user_url(@wall.admin) %>
      </div>
    </div>
  </div>

  <div class="seven columns wall-view-header" style="padding: 10px;">
    <h1 style="margin: 0px;"><%= @wall.name %></h1>

    <% if @wall.description.present? %>
      <p><%= @wall.description %></p>
    <% end %>

    <%= render :partial => "wall/input_box", :locals => { :wall_user => @user, :post_url => wall_ajax_public_post_url, :header_text => "Post to #{@wall.name}", :columns => "nine" } %>

    <%#= link_to_function image_tag("fb_share_button.jpg"), "Groovesy.FBShare('#{@wall.name} on Groovesy.com', '#{view_wall_url(@wall.slug)}', '#{@wall.description}')", :id => "fb_share_button" %>
  </div>

  <div class="two columns" style="padding: 10px;">
    <% if !@user.nil? %>
      <div class="right">
        <% if !@user.member_of?(@wall) %>
          <%= button_to "Subscribe To this Wall", wall_ajax_subscribe_url(@wall), :remote => true, :class => "small button" %>
        <% else %>
          <%= button_to "Unsubscribe", wall_ajax_unsubscribe_url(@wall), :remote => true, :class => "small button" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="row" style="margin-bottom: 10px;">
  <div class="twelve columns">

    <div class="shadow clearfix" style="background-color: #EFEFEF; padding: 5px;">

      <%= submit_tag "Share", :id => "share_post", :class => "small button right" %>

      <div id="links" class="hide">
        <%= link_to image_tag("x_button_light.png", :alt => ""), "javascript: void();", { :id => "close_button", :class => "right" } %>
        <ul>
          <li><label for="url" style="padding-top: 4px;">Direct Link:</label> <%= text_field_tag :url, "#{view_wall_url(@wall.slug)}", :onclick => "$('#url').select();" %></li>
          <li>
            <label>Facebook:</label>
            <%= render :partial => "shared/fb_share_button", :locals => { :type => :wall, :wall => @wall } %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% cache [@wall, "posts"] do %>
  <div class="row">
    <div class="twelve columns">
      <div id="posts_container" class="clearfix">
        <% @posts.each do | post | %>
          <%= render :partial => "streams/post", :locals => { :post => post, :context => "public_wall", :render_context => "isotope", :show_dest => false } %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% content_for :right_sidebar do %>
  <% cache [@wall, "members"] do %>
    <div id="wall_members" class="groovesy-panel">
      <h3>Wall Members</h3>
      <div class="clearfix">
        <% @wall.wall_users.each do | user | %>
          <%= link_to profile_user_url(user, :alt => user.first_and_last_name) do %><%= render_profile_photo( user, "32x32" ) %><% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<%= render :partial => "shared/likes_hide" %>

<% content_for :javascripts do %>
  <script type="text/javascript">
    <% @posts.each do | post | %>
    var current_comments_page_<%= post.id %> = 0;
    <% end %>
  </script>
<% end %>